### ISSUE TITLE
Síntesis Buenas Practicas en gestión de proyectos de software

### ISSUE THREAD

**Issue by antoniio** [SistemasTecTlaxiaco/sintesis-antoniio#2]
[Sintesis.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-antoniio/files/7132883/Sintesis.pdf)

**Comment by Joel343** [comment]
20
1.- Hace falta referencias

**Comment by Joel343** [comment]
100%

**Comment by josealfredo79** [comment]
La calificación no puede ser 100%, debe ser 20%
